package src.main.java;

public enum AlgorithmType {
    BRUTE_FORCE,
    DECREASE_AND_CONQUER,
    DIVIDE_AND_CONQUER,
    TRANSFORM_AND_CONQUER,
    DYNAMIC_PROGRAMMING,
    GREEDY,
    ITERATIVE_IMPROVEMENT,
    TIME_AND_SPACE_TRADE_OFF
}